import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog it
        </h1>

        <p className={styles.description}>
          Publish your blogs here
        </p>
      </main>

      <div className={styles.blogs}>
        <div className={styles.blogItem}>
          <h1>How to learn JS?</h1>
          <p>Click here now</p>
        </div>
        <div className={styles.blogItem}>
          <h1>How to learn React?</h1>
          <p>Click here now</p>
        </div>
        <div className={styles.blogItem}>
          <h1>How to learn Next?</h1>
          <p>Click here now</p>
        </div>
      </div>
    </div>
  )
}
